server: Server.h Server.cpp EulerAlgorithm.h EulerAlgorithm.cpp GraphAlgorithm.h GraphAlgorithm.cpp Graph.h Graph.cpp HamiltonCircuitAlgorithm.h HamiltonCircuitAlgorithm.cpp MaxCliqueAlgorithm.h MaxCliqueAlgorithm.cpp MSTWeightAlgorithm.h MSTWeightAlgorithm.cpp NumberOfCliquesAlgorithm.h NumberOfCliquesAlgorithm.cpp GraphUtilities.h GraphUtilities.cpp GraphAlgorithmFactory.h GraphAlgorithmFactory.cpp
	g++ Server.cpp EulerAlgorithm.cpp GraphAlgorithm.cpp Graph.cpp HamiltonCircuitAlgorithm.cpp MaxCliqueAlgorithm.cpp MSTWeightAlgorithm.cpp NumberOfCliquesAlgorithm.cpp GraphUtilities.cpp GraphAlgorithmFactory.cpp -o server

client: Client.h Client.cpp
	g++ Client.cpp -o client

